In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as polt

cancer = pd.read_csv('cancer.csv')


from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
cancer['Class'] = labelencoder_X.fit_transform(cancer.Class)
cancer['Age'] = labelencoder_X.fit_transform(cancer.Age)
cancer['Menopause'] = labelencoder_X.fit_transform(cancer.Menopause)
cancer['Tsize'] = labelencoder_X.fit_transform(cancer.Tsize)
cancer['NodeCaps'] = labelencoder_X.fit_transform(cancer.NodeCaps)
cancer['Breast'] = labelencoder_X.fit_transform(cancer.Breast)
cancer['BreastQuad'] = labelencoder_X.fit_transform(cancer.BreastQuad)
cancer['Irradi'] = labelencoder_X.fit_transform(cancer.Irradi)

cancer.drop(cancer.columns[[4]], axis = 1, inplace=True)

X=cancer.drop("Class",axis=1)
Y=cancer["Class"]

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

#from sklearn.naive_bayes import GaussianNB
#gnb = GaussianNB()

from sklearn import svm
classifier=svm.SVC(kernel='linear',gamma='auto',C=2)

classifier.fit(X_train,Y_train)
Y_predict=classifier.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_predict))

from sklearn import metrics
print("confusion matrix:")
print(metrics.confusion_matrix(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       0.78      0.84      0.81        61
           1       0.52      0.44      0.48        25

    accuracy                           0.72        86
   macro avg       0.65      0.64      0.64        86
weighted avg       0.71      0.72      0.71        86

confusion matrix:
[[51 10]
 [14 11]]


In [3]:
from sklearn.svm import SVC
pclassifier = SVC(kernel='poly', degree=8, gamma='auto')
pclassifier.fit(X_train,Y_train)
Y_predict=pclassifier.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_predict))

from sklearn import metrics
print("confusion matrix:")
print(metrics.confusion_matrix(Y_test,Y_predict))

              precision    recall  f1-score   support

           0       0.76      0.74      0.75        61
           1       0.41      0.44      0.42        25

    accuracy                           0.65        86
   macro avg       0.59      0.59      0.59        86
weighted avg       0.66      0.65      0.65        86

confusion matrix:
[[45 16]
 [14 11]]


In [4]:
import time

from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf', gamma='auto')

start = time.time()
svclassifier.fit(X_train, Y_train)
Y_predict=svclassifier.predict(X_test)
end = time.time()


print("Execution time: %s seconds \n" % "{0:.5}".format(end-start))

print("classification report: ")


from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_predict))

from sklearn import metrics
print("confusion matrix:")
print(metrics.confusion_matrix(Y_test,Y_predict))

mean_absolute_error = metrics.mean_absolute_error(Y_test,Y_predict, sample_weight=None, multioutput='uniform_average')
print("Mean absolute error: ",mean_absolute_error)

kappa_score = metrics.cohen_kappa_score(Y_test,Y_predict, labels=None, weights=None, sample_weight=None)
print("kappa score: ",kappa_score)

Execution time: 0.0050223 seconds 

classification report: 
              precision    recall  f1-score   support

           0       0.73      1.00      0.85        61
           1       1.00      0.12      0.21        25

    accuracy                           0.74        86
   macro avg       0.87      0.56      0.53        86
weighted avg       0.81      0.74      0.66        86

confusion matrix:
[[61  0]
 [22  3]]
Mean absolute error:  0.2558139534883721
kappa score:  0.16209034543844103


In [5]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid', gamma='auto')
svclassifier.fit(X_train, Y_train)
Y_predict=svclassifier.predict(X_test)

from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_predict))

from sklearn import metrics
print("confusion matrix:")
print(metrics.confusion_matrix(Y_test,Y_predict))


              precision    recall  f1-score   support

           0       0.70      0.93      0.80        61
           1       0.20      0.04      0.07        25

    accuracy                           0.67        86
   macro avg       0.45      0.49      0.43        86
weighted avg       0.56      0.67      0.59        86

confusion matrix:
[[57  4]
 [24  1]]


In [ ]:
features_mean= list(data.columns[1:11])
